version: '2.1'

networks:
  fabric_network:
    external:
      name: fabric_network

services:
  # 后端
  fabric-realty.server:
    # 默认使用我编译好放在 Docker Hub 上的镜像： togettoyou/fabric-realty.server:latest
    image: togettoyou/fabric-realty.server:latest
    # 如改动代码需要自行编译（进入 server 执行 ./build.sh ）并使用本地镜像：fabric-realty.server:latest
    # image: fabric-realty.server:latest
    container_name: fabric-realty.server
    ports:
      - "8888:8888"
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/usr/share/zoneinfo/Asia/Shanghai
      - ./../network/crypto-config:/network/crypto-config
    networks:
      - fabric_network
  # 前端
  fabric-realty.web:
    # 默认使用我编译好放在 Docker Hub 上的镜像： togettoyou/fabric-realty.web:latest
    image: togettoyou/fabric-realty.web:latest
    # 如改动代码需要自行编译（进入 web 执行 ./build.sh ）并使用本地镜像：fabric-realty.web:latest
    # image: fabric-realty.web:latest
    container_name: fabric-realty.web
    ports:
      - "8000:80"
    networks:
      - fabric_network